#!/bin/bash

DATAPATH=$1 # no spaces!
CITY=$2
#YEAR=$3

Og=`pwd` #recording original directory where script is run


cd $DATAPATH
CITYFILE="$DATAPATH/`grep -i -l -m 2 $CITY *`" # - m 2

if [[ "x$CITYFILE" == "x$DATAPATH/" ]]; then
	echo "City $CITY not found, exiting"
	exit 1
fi
#//make a temporary directory that is deleted end of script
mkdir $Og/SmhiCleaner/CleanerOutputs
#//change current directory to CleanerOutputs where files will be produced by smhicleaner.sh
cd $Og/SmhiCleaner/CleanerOutputs

$Og/SmhiCleaner/smhicleaner.sh $CITYFILE > ./shmicleaner.log 2>&1

RAWFILENAME=$(basename $CITYFILE)

RAWFILENAME="rawdata_${RAWFILENAME}"

cp $RAWFILENAME $Og/code/ClnData/Clean$CITY.csv

rm * #//remove the files generated by smhicleaner in the temporary folder CleanerOutputs 

cd $Og

rmdir $Og/SmhiCleaner/CleanerOutputs #//delete the empty temporary folder
